routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'AudioController@home')->name('home');
//    ->middleware('auth');

Route::get('/download/{audio}', 'AudioController@getDownload')->name('download');
Route::post('/send-code', 'ActivationCodeController@sendCode')->name('verify.code.send');
Auth::routes();

Route::prefix('portal')->name('portal.')->middleware('auth')->group(function () {
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'AudioController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AudioController@all')->name('home');
            Route::get('/create', 'AudioController@create')->name('create');
            Route::get('/pending', 'AudioController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AudioController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
        });
    });
    Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AdminController@allAudio')->name('home');
            Route::get('/create', 'AdminController@create')->name('create');
            Route::get('/pending', 'AdminController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AdminController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
            Route::get('/publish/{audio}', 'AdminController@publish')->name('publish');
            Route::get('/reject/{audio}', 'AdminController@reject')->name('reject');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Audio.php
<?php

namespace App\Models;

use Illuminate\Auth\Access\Gate;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Audio extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $primaryKey = 'audio_id';

    public function scopePending($scope)
    {
        return $scope->where('status', '1');
    }
    public function scopeActive($scope)
    {
        return $scope->where('status', '2');
    }
    public function scopeOwner($scope)
    {
        return $scope->where('user_id', \Auth::id());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function isOwner()
    {
        if ($this->user_id == \Auth::id()){
            return true;

        }else {
            if (\Auth::user()->level == '1') {
                return true;
            }
            return true;
        }
    }
}

app/Http/Controllers/AudioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Audio;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image;
use Owenoj\LaravelGetId3\GetId3;
use wapmorgan\MediaFile\MediaFile;
use wapmorgan\Mp3Info\Mp3Info;
class AudioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function audios(Request $request)
    {
        $audios = Audio::active()->latest()->with('user')->get();
        return response()->json($audios, 200);
    }
    public function getDownload(Audio $audio){

//        $file = public_path().;
        return Response::download($audio->file);
    }
    public function home()
    {
        $audios = Audio::active()->latest()->get();
        return view('pages.index', compact('audios'));
    }
    public function index()
    {
        return view('portal.user.index');
    }

    public function all()
    {
        if (\Auth::user()->isAdmin()){
            $audios = Audio::latest()->paginate(20);
        }else {
            $audios = Audio::owner()->latest()->paginate(20);
        }
        return view('portal.user.audio.index', ['audios'=> $audios]);
    }


    public function pending()
    {
        if (\Auth::user()->isAdmin()){
            $audios = Audio::latest()->pending()->paginate(20);
        }else {
            $audios = Audio::owner()->pending()->latest()->paginate(20);
        }
        return view('portal.user.audio.pending', ['audios'=> $audios]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Audio $audio)
    {
        return view('portal.user.audio.create', ['audio' => $audio]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'audio_file' => ['required', 'string'],
            'cover' => ['required', 'string'],
            'caption' => ['required', 'string', 'min:3'],
        ], [
            'audio_file.required' => "Please select an audio file.",
        ]);
        if($validator->fails()){
            return Redirect::back()->withErrors($validator->errors());
        }

        $audio = Audio::create([
            'user_id' => \Auth::id(),
            'caption' => $request->caption,
            'file' => $request->audio_file,
            'image' => $request->cover,
            'duration' => $request->duration,
            'status' => $request->status,
        ]);
        if ($audio){
            Session::flash('success', "Audio Shared Successfully!!");
            return Redirect::back();
        } else {
            Session::flash('error', "Audio Shared Failed!!");
            return Redirect::back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function show(Audio $audio)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function edit(Audio $audio)
    {
        if ($audio->isOwner()) {
            return view('portal.user.audio.create', ['audio' => $audio]);
        }
        Session::flash('error', "Access Denied!!");
        return Redirect::route('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function uploadAudio(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'audio' => ['required', 'max:10212'],
        ], [
            'audio.required' => "Please select an audio file.",
        ]);
        if($validator->fails()){
            return response(['errors' => $validator->errors()], 422);
        }
        if ($request->hasfile('audio')) {
            $time = Carbon::now();
            $file = $request->file('audio');
            $track = GetId3::fromUploadedFile($request->file('audio'));
            $duration = $track->getPlaytime();
            $extension = $track->getFileFormat();
            $ext_array = ['mp3','ogg','wav','mp4','wma','aac'];
            if(!in_array($extension, $ext_array)){
                return response(['errors' => ['audio' => ['Invalid Audio Format']]], 422);
            }else {
                // Creating the directory, for example, if the date = 18/10/2017, the directory will be 2017/10/
                $directory = 'audio/file/' . date_format($time, 'Y') . '/' . date_format($time, 'm');
                File::ensureDirectoryExists($directory);
                // Creating the file name: random string followed by the day, random number and the hour
                $filename = date_format($time, 'd') . rand(1, 9) . date_format($time, 'h') . "." . $extension;
                if ($file->move($directory, $filename)) {
                    $urls = $directory . '/' . $filename;
//                $size = $file->getSize();

                    return response()->json(['message' => 'Uploaded', 'url' => $urls, 'duration' => $duration, 'ext' => $extension], 200);
                }
                return response()->json(['message' => 'Upload Failed'], 422);
            }
        }
    }

    public function uploadCover(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'image' => ['required', 'mimes:jpg,png,bmp', 'max:5125'],
        ], [
            'image.required' => "Please provide your full name.",
            'image.mimes' => "Invalid Image Format",
        ]);
        if($validator->fails()){
            return response(['errors' => $validator->errors()], 422);
        }
        if ($request->hasfile('image')) {
            $time = Carbon::now();
            $image = $request->file('image');
            $extension = $image->getClientOriginalExtension();
            // Creating the directory, for example, if the date = 18/10/2017, the directory will be 2017/10/
            $directory = 'audio/cover/'.date_format($time, 'Y') . '/' . date_format($time, 'm');
            File::ensureDirectoryExists($directory);
            // Creating the file name: random string followed by the day, random number and the hour
            $filename = date_format($time, 'd') . rand(1, 9).'-'. \Str::random(9) . date_format($time, 'h') . "." . $extension;
            $location = $directory.'/'.$filename;

            if(Image::make($image)->save($location)){
                return response()->json(['message' => 'Uploaded', 'image' => asset($location), 'imageName' => $location], 200);
            }
            return response()->json(['message' => 'Failed'], 422);
        }
    }
    public function update(Request $request, Audio $audio)
    {
        $validator = Validator::make($request->all(), [
            'caption' => ['required', 'string', 'min:3'],
        ]);
        if($validator->fails()){
            return Redirect::back()->withInput()->withErrors($validator->errors());
        }
        if (is_null($request->audio_file)){
            $audio_file = $audio->file;
        }else{
            $audio_file = $request->audio_file;
        }
        if (is_null($request->cover)){
            $cover = $audio->image;
        }else{
            $cover = $request->cover;
        }
        if (is_null($request->duration)){
            $duration = $audio->duration;
        }else{
            $duration = $request->duration;
        }
        $update = $audio->update(
            [
                'caption' => $request->caption,
                'image' => $cover,
                'file' => $audio_file,
                'status' => $request->status,
                'duration' => $duration,
                'user_id' => \Auth::id(),
            ],
            $request->except('_token','_method'));
        if($update){
            Session::flash('success', "Audio Data Updated Successfully!!");
            return Redirect::back();
        } else {
            Session::flash('error', "Audio Data Update Failed!!");
            return Redirect::back();
        }
    }
    public function formatSeconds( $seconds )
    {
        $hours = 0;
        $milliseconds = str_replace( "0.", '', $seconds - floor( $seconds ) );

        if ( $seconds > 3600 )
        {
            $hours = floor( $seconds / 3600 );
        }
        $seconds = $seconds % 3600;


        return gmdate( 'i:s', $seconds );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Audio $audio)
    {
        if ($audio->isOwner()) {

            if (File::exists($audio->file)) {
                File::delete([$audio->file, $audio->image]);
            }
            if ($audio->delete()) {
                Session::flash('success', "Audio File Deleted Successfully!!");
                return Redirect::back();
            } else {
                Session::flash('error', "Audio File Deletion Failed!!");
                return Redirect::back();
            }
        }
        Session::flash('error', "Access Denied!!");
        return Redirect::route('home');
    }
}

resources/views/portal/admin/audio/edit.blade.php
@extends('portal.admin.layout')
@section('title', $provider->name)
@section('content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <form class="intro-y col-span-12 lg:col-span-8" method="post" action="{{ route('portal.admin.provider.update', $provider->provider_id) }}">
        <div class="alert @if (Session::has('success')) alert-success @elseif(Session::has('error')) alert-danger @else d-none @endif alert-dismissible show flex items-center mb-2" role="alert">
            @if(Session::has('success')) <i data-feather="alert-circle" class="w-6 h-6 mr-2"></i>@elseif(Session::has('error'))  <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> @endif {{ Session::get('message') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
        </div>
        @csrf()
        @method('PATCH')
        <!-- BEGIN: Form Layout -->
        <div class="intro-y box p-5">
            <div class="my-5">
                <label for="crud-form-1" class="form-label">Title</label>
                <input id="crud-form-1" type="text" value="{{ old('title', $user->provider_title) }}" class="form-control w-full" name="title" placeholder="Client's Title">
            </div>
            <div class="sm:grid grid-cols-2 gap-2 my-5">
                <div class="">
                    <label for="crud-form-1" class="form-label">First Name</label>
                    <input id="crud-form-1" value="{{ old('fname', $user->fname) }}" type="text" class="form-control w-full" name="fname" placeholder="John">
                </div>
                <div class="">
                    <label for="crud-form-1" class="form-label">Last Name</label>
                    <input id="crud-form-1" value="{{ old('lname', $user->lname) }}" type="text" class="form-control w-full" name="lname" placeholder="Doe">
                </div>
            </div>
            <div class="my-5">
                <label for="crud-form-1" class="form-label">Username</label>
                <input id="crud-form-1" value="{{ old('username', $user->username) }}" type="text" class="form-control w-full" name="username" placeholder="johndoe">
            </div>
            <div class="sm:grid grid-cols-2 gap-2 my-5">
                <div class="">
                    <label for="crud-form-1" class="form-label">Email Address</label>
                    <input id="crud-form-1" value="{{ old('email', $user->email) }}" type="email" class="form-control w-full" name="email" placeholder="johndoe@example.com">
                </div>
                <div class="">
                    <label for="crud-form-1" class="form-label">Phone Number</label>
                    <input id="crud-form-1" type="tel" value="{{ old('tel', $user->tel) }}" class="form-control w-full" name="tel" placeholder="+234808989009">
                </div>
            </div>
            <div class="my-5">
                <label for="crud-form-1" class="form-label">Name of Institution</label>
                <input id="crud-form-1" type="text" value="{{ old('name', $provider->name) }}" class="form-control w-full" name="institution" placeholder="Harvard University">
            </div>
            <div class="my-5">
                <label for="crud-form-1" class="form-label">Position</label>
                <input id="crud-form-1" value="{{ old('role', $user->provider_role) }}" type="text" class="form-control w-full" name="position" placeholder="COO">
            </div>
            <div class="my-5">
                <label for="crud-form-1" class="form-label">Sub Expiry Date</label>
                <input id="crud-form-1" type="text" value="{{ old('expires_at', $provider->expires_at->format('d M, Y')) }}"  class="form-control w-full datepicker" data-single-mode="true" name="expires_at" placeholder="12 Mar, 2021">
            </div>
            <div class="mt-3">
                <label>Active Status</label>
                <div class="mt-2">
                    <input type="checkbox" class="form-check-switch" value="2" name="status" @if($provider->status > 1) checked @endif>
                </div>
            </div>
            <div class="text-right mt-5">
                <button type="button" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                <button type="submit" class="btn btn-primary w-24">Save</button>
            </div>
        </div>
        <!-- END: Form Layout -->
    </form>
</div>
@endsection

resources/views/portal/admin/audio/index.blade.php
@extends('portal.admin.layout')
@section('title', 'All Audio Shared')
@section('content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.admin.audio.create') }}" class="btn btn-primary shadow-md mr-2">Upload New Audio</a>
        <div class="dropdown">
            <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
        </div>
        <div class="hidden md:block mx-auto text-gray-600">Showing @if($audios->total() < 2) 1 @else 1 to {{ $audios->total() }} @endif of {{ $audios->total() }} entries</div>

    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        @if (count($audios) > 0)
            <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">Cover</th>
                <th class="whitespace-nowrap">Caption</th>
                <th class="text-center whitespace-nowrap">Created By</th>
                <th class="text-center whitespace-nowrap">Status</th>
                <th class="text-center whitespace-nowrap">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($audios as $audio)

            <tr class="intro-x">
                <td class="w-40">
                    <div class="flex">
                        <div class="w-10 h-10 image-fit zoom-in">
                            <img alt="{{ \Str::limit(\Str::slug($audio->caption), 10) }}" class="tooltip rounded-full" src="{{ asset($audio->image) }}" title="{{ \Str::limit($audio->caption, 10) }}">
                        </div>
                    </div>
                </td>
                <td>
                    <a href="" class="font-medium whitespace-nowrap">{{ \Str::limit($audio->caption, 10) }}</a>
                </td>
                <td class="text-center">{{ $audio->user->name }}</td>
                <td class="w-40">
                    @if($audio->status == '0')
                        <span class="text-theme-6"> Draft</span>
                    @elseif($audio->status == '1')
                        <span class="text-theme-12"> Pending</span>
                    @elseif($audio->status == '2')
                        <span class="text-theme-9"> Published</span>
                    @endif
                </td>
                <td class="table-report__action w-56">
                    <div class="flex justify-center items-center">
                        <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.edit', $audio->audio_id) }}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                        @if($audio->status == '1')
                            <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.publish', $audio->audio_id) }}"> <i data-feather="check" class="w-4 h-4 mr-1"></i> Publish </a>
                        @elseif($audio->status == '2')
                            <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.reject', $audio->audio_id) }}"> <i data-feather="x-circle" class="w-4 h-4 mr-1"></i> Reject </a>
                        @endif
                        <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal{{ $audio->audio_id }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                    </div>
                </td>
            </tr>
            @push('audio-delete-modal')
                @include('portal.admin.inc.audio-delete-modal', ['audio' => $audio])
            @endpush
            @endforeach

            </tbody>
        </table>
        @else
            <div class="col-12 alert alert-danger"><i data-feather="alert-octagon"></i> Oops!! No Audio Record Found.</div>
        @endif
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
        <ul class="pagination">
            {!! $audios->links() !!}
        </ul>
    </div>
    <!-- END: Pagination -->
</div>

@endsection
@section('scripts')
    <script>
        $('.item').on('change', function () {
            alert('');
            var val = $(this).val();
            window.location = window.location.href+'?items='+val;
        });
    </script>
@endsection

resources/views/portal/admin/audio/pending.blade.php
@extends('portal.admin.layout')
@section('title', 'All Audio Shared')
@section('content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.admin.audio.create') }}" class="btn btn-primary shadow-md mr-2">Upload New Audio</a>
        <div class="dropdown">
            <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
        </div>
        <div class="hidden md:block mx-auto text-gray-600">Showing @if($audios->total() < 2) 1 @else 1 to {{ $audios->total() }} @endif of {{ $audios->total() }} entries</div>

    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        @if (count($audios) > 0)
            <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">Cover</th>
                <th class="whitespace-nowrap">Caption</th>
                <th class="text-center whitespace-nowrap">Created By</th>
                <th class="text-center whitespace-nowrap">Status</th>
                <th class="text-center whitespace-nowrap">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($audios as $audio)

            <tr class="intro-x">
                <td class="w-40">
                    <div class="flex">
                        <div class="w-10 h-10 image-fit zoom-in">
                            <img alt="{{ \Str::limit(\Str::slug($audio->caption), 10) }}" class="tooltip rounded-full" src="{{ asset($audio->image) }}" title="{{ \Str::limit($audio->caption, 10) }}">
                        </div>
                    </div>
                </td>
                <td>
                    <a href="" class="font-medium whitespace-nowrap">{{ \Str::limit($audio->caption, 10) }}</a>
                </td>
                <td class="text-center">{{ $audio->user->name }}</td>
                <td class="w-40">
                    @if($audio->status == '0')
                        <span class="text-theme-6"> Draft</span>
                    @elseif($audio->status == '1')
                        <span class="text-theme-12"> Pending</span>
                    @elseif($audio->status == '2')
                        <span class="text-theme-9"> Published</span>
                    @endif
                </td>
                <td class="table-report__action w-56">
                    <div class="flex justify-center items-center">
                        <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.edit', $audio->audio_id) }}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                        @if($audio->status == '1')
                            <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.publish', $audio->audio_id) }}"> <i data-feather="check" class="w-4 h-4 mr-1"></i> Publish </a>
                        @elseif($audio->status == '2')
                            <a class="flex items-center mr-3" href="{{ route('portal.admin.audio.reject', $audio->audio_id) }}"> <i data-feather="x-circle" class="w-4 h-4 mr-1"></i> Reject </a>
                        @endif
                        <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal{{ $audio->audio_id }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                    </div>
                </td>
            </tr>
            @push('audio-delete-modal')
                @include('portal.admin.inc.audio-delete-modal', ['audio' => $audio])
            @endpush
            @endforeach

            </tbody>
        </table>
        @else
            <div class="col-12 alert alert-danger"><i data-feather="alert-octagon"></i> Oops!! No Audio Record Found.</div>
        @endif
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
        <ul class="pagination">
            {!! $audios->links() !!}
        </ul>
    </div>
    <!-- END: Pagination -->
</div>

@endsection
@section('scripts')
    <script>
        $('.item').on('change', function () {
            alert('');
            var val = $(this).val();
            window.location = window.location.href+'?items='+val;
        });
    </script>
@endsection