routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'AudioController@home')->name('home');
//    ->middleware('auth');

Route::get('/download/{audio}', 'AudioController@getDownload')->name('download');
Route::post('/send-code', 'ActivationCodeController@sendCode')->name('verify.code.send');
Auth::routes();

Route::prefix('portal')->name('portal.')->middleware('auth')->group(function () {
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'AudioController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AudioController@all')->name('home');
            Route::get('/create', 'AudioController@create')->name('create');
            Route::get('/pending', 'AudioController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AudioController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
        });
    });
    Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AdminController@allAudio')->name('home');
            Route::get('/create', 'AdminController@create')->name('create');
            Route::get('/pending', 'AdminController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AdminController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
            Route::get('/publish/{audio}', 'AdminController@publish')->name('publish');
            Route::get('/reject/{audio}', 'AdminController@reject')->name('reject');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/Audio.php
<?php

namespace App\Models;

use Illuminate\Auth\Access\Gate;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Audio extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $primaryKey = 'audio_id';

    public function scopePending($scope)
    {
        return $scope->where('status', '1');
    }
    public function scopeActive($scope)
    {
        return $scope->where('status', '2');
    }
    public function scopeOwner($scope)
    {
        return $scope->where('user_id', \Auth::id());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function isOwner()
    {
        if ($this->user_id == \Auth::id()){
            return true;

        }else {
            if (\Auth::user()->level == '1') {
                return true;
            }
            return true;
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'level',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function audio()
    {
        return $this->hasMany(Audio::class);
    }

    public function isAdmin()
    {
        if (\Auth::check()){
            if (\Auth::user()->level == '1'){
                return true;
            }
            return false;
        }
        return false;
    }
}

app/Http/Controllers/AudioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Audio;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\Facades\Image;
use Owenoj\LaravelGetId3\GetId3;
use wapmorgan\MediaFile\MediaFile;
use wapmorgan\Mp3Info\Mp3Info;
class AudioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function audios(Request $request)
    {
        $audios = Audio::active()->latest()->with('user')->get();
        return response()->json($audios, 200);
    }
    public function getDownload(Audio $audio){

//        $file = public_path().;
        return Response::download($audio->file);
    }
    public function home()
    {
        $audios = Audio::active()->latest()->get();
        return view('pages.index', compact('audios'));
    }
    public function index()
    {
        return view('portal.user.index');
    }

    public function all()
    {
        if (\Auth::user()->isAdmin()){
            $audios = Audio::latest()->paginate(20);
        }else {
            $audios = Audio::owner()->latest()->paginate(20);
        }
        return view('portal.user.audio.index', ['audios'=> $audios]);
    }


    public function pending()
    {
        if (\Auth::user()->isAdmin()){
            $audios = Audio::latest()->pending()->paginate(20);
        }else {
            $audios = Audio::owner()->pending()->latest()->paginate(20);
        }
        return view('portal.user.audio.pending', ['audios'=> $audios]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Audio $audio)
    {
        return view('portal.user.audio.create', ['audio' => $audio]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'audio_file' => ['required', 'string'],
            'cover' => ['required', 'string'],
            'caption' => ['required', 'string', 'min:3'],
        ], [
            'audio_file.required' => "Please select an audio file.",
        ]);
        if($validator->fails()){
            return Redirect::back()->withErrors($validator->errors());
        }

        $audio = Audio::create([
            'user_id' => \Auth::id(),
            'caption' => $request->caption,
            'file' => $request->audio_file,
            'image' => $request->cover,
            'duration' => $request->duration,
            'status' => $request->status,
        ]);
        if ($audio){
            Session::flash('success', "Audio Shared Successfully!!");
            return Redirect::back();
        } else {
            Session::flash('error', "Audio Shared Failed!!");
            return Redirect::back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function show(Audio $audio)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function edit(Audio $audio)
    {
        if ($audio->isOwner()) {
            return view('portal.user.audio.create', ['audio' => $audio]);
        }
        Session::flash('error', "Access Denied!!");
        return Redirect::route('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function uploadAudio(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'audio' => ['required', 'max:10212'],
        ], [
            'audio.required' => "Please select an audio file.",
        ]);
        if($validator->fails()){
            return response(['errors' => $validator->errors()], 422);
        }
        if ($request->hasfile('audio')) {
            $time = Carbon::now();
            $file = $request->file('audio');
            $track = GetId3::fromUploadedFile($request->file('audio'));
            $duration = $track->getPlaytime();
            $extension = $track->getFileFormat();
            $ext_array = ['mp3','ogg','wav','mp4','wma','aac'];
            if(!in_array($extension, $ext_array)){
                return response(['errors' => ['audio' => ['Invalid Audio Format']]], 422);
            }else {
                // Creating the directory, for example, if the date = 18/10/2017, the directory will be 2017/10/
                $directory = 'audio/file/' . date_format($time, 'Y') . '/' . date_format($time, 'm');
                File::ensureDirectoryExists($directory);
                // Creating the file name: random string followed by the day, random number and the hour
                $filename = date_format($time, 'd') . rand(1, 9) . date_format($time, 'h') . "." . $extension;
                if ($file->move($directory, $filename)) {
                    $urls = $directory . '/' . $filename;
//                $size = $file->getSize();

                    return response()->json(['message' => 'Uploaded', 'url' => $urls, 'duration' => $duration, 'ext' => $extension], 200);
                }
                return response()->json(['message' => 'Upload Failed'], 422);
            }
        }
    }

    public function uploadCover(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'image' => ['required', 'mimes:jpg,png,bmp', 'max:5125'],
        ], [
            'image.required' => "Please provide your full name.",
            'image.mimes' => "Invalid Image Format",
        ]);
        if($validator->fails()){
            return response(['errors' => $validator->errors()], 422);
        }
        if ($request->hasfile('image')) {
            $time = Carbon::now();
            $image = $request->file('image');
            $extension = $image->getClientOriginalExtension();
            // Creating the directory, for example, if the date = 18/10/2017, the directory will be 2017/10/
            $directory = 'audio/cover/'.date_format($time, 'Y') . '/' . date_format($time, 'm');
            File::ensureDirectoryExists($directory);
            // Creating the file name: random string followed by the day, random number and the hour
            $filename = date_format($time, 'd') . rand(1, 9).'-'. \Str::random(9) . date_format($time, 'h') . "." . $extension;
            $location = $directory.'/'.$filename;

            if(Image::make($image)->save($location)){
                return response()->json(['message' => 'Uploaded', 'image' => asset($location), 'imageName' => $location], 200);
            }
            return response()->json(['message' => 'Failed'], 422);
        }
    }
    public function update(Request $request, Audio $audio)
    {
        $validator = Validator::make($request->all(), [
            'caption' => ['required', 'string', 'min:3'],
        ]);
        if($validator->fails()){
            return Redirect::back()->withInput()->withErrors($validator->errors());
        }
        if (is_null($request->audio_file)){
            $audio_file = $audio->file;
        }else{
            $audio_file = $request->audio_file;
        }
        if (is_null($request->cover)){
            $cover = $audio->image;
        }else{
            $cover = $request->cover;
        }
        if (is_null($request->duration)){
            $duration = $audio->duration;
        }else{
            $duration = $request->duration;
        }
        $update = $audio->update(
            [
                'caption' => $request->caption,
                'image' => $cover,
                'file' => $audio_file,
                'status' => $request->status,
                'duration' => $duration,
                'user_id' => \Auth::id(),
            ],
            $request->except('_token','_method'));
        if($update){
            Session::flash('success', "Audio Data Updated Successfully!!");
            return Redirect::back();
        } else {
            Session::flash('error', "Audio Data Update Failed!!");
            return Redirect::back();
        }
    }
    public function formatSeconds( $seconds )
    {
        $hours = 0;
        $milliseconds = str_replace( "0.", '', $seconds - floor( $seconds ) );

        if ( $seconds > 3600 )
        {
            $hours = floor( $seconds / 3600 );
        }
        $seconds = $seconds % 3600;


        return gmdate( 'i:s', $seconds );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Audio  $audio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Audio $audio)
    {
        if ($audio->isOwner()) {

            if (File::exists($audio->file)) {
                File::delete([$audio->file, $audio->image]);
            }
            if ($audio->delete()) {
                Session::flash('success', "Audio File Deleted Successfully!!");
                return Redirect::back();
            } else {
                Session::flash('error', "Audio File Deletion Failed!!");
                return Redirect::back();
            }
        }
        Session::flash('error', "Access Denied!!");
        return Redirect::route('home');
    }
}

resources/views/portal/user/audio/create.blade.php
@extends('portal.user.layout')
@section('title', 'Upload Audio')
@section('content')
    @if($audio->audio_id)
        <form class="intro-y col-span-12 lg:col-span-8" method="post" action="{{ route('portal.user.audio.update', $audio->audio_id) }}">
            @method('patch')
            @else
                <form class="intro-y col-span-12 lg:col-span-8" method="post" action="{{ route('portal.user.audio.store') }}" enctype="multipart/form-data">
                @endif
                @include('portal.user.inc.alert')
                @csrf()
                <!-- BEGIN: Form Layout -->
                    <div class="intro-y box p-5">
                        <div class="my-5">
                            <label for="caption" class="form-label">Caption <b class="text-theme-6">*</b></label>
                            <textarea id="caption" rows="3" class="form-control w-full" name="caption" placeholder="Caption" required>
                                {{ old('caption', $audio->caption) }}
                            </textarea>
                            @error('caption')
                            <span class="text-theme-6 mt-2" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="my-5">
                            <label for="crud-form-1" class="form-label">Select Audio Cover Image <b class="text-theme-6">*</b></label>

                                <input name="image" type="file" id="imageFile"  class="form-control w-full"/>
                            <input type="hidden" name="cover" id="coverimage" value="{{ old('image', $audio->image) }}">
                            @error('cover')
                            <span class="text-theme-6 mt-2" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <small class="text-theme-6 font-bold">Supported Image formats: jpg,png,bmp are allowed and not above 5MB in size</small>
                        </div>
                        <div class="form-group mt-4">
                            <div class="progress h-4 rounded" style="display: none;" id="progress">
                                <div class="progress-bar bg-theme-6" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" ></div>
                            </div>
                        </div>
                        <div class="rounded mt-5 p-1" id="img-display" style="height: 180px; width: 180px; background-color: #F1F5F8; display: none !important;  "></div>
                        <div class="my-5">
                            <label for="crud-form-1" class="form-label">Select Audio File <b class="text-theme-6">*</b></label>

                                <input name="audio" type="file" id="audioFile"  class="form-control w-full" accept="audio/*"/>
                            <input type="hidden" name="audio_file" id="audio" required>
                            <input type="hidden" name="duration" value="{{ old('duration', $audio->duration) }}" id="duration" required>
                            @error('audio_file')
                            <span class="text-theme-6 mt-2" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <small class="text-theme-6 font-bold">Only Audio formats: mp3,ogg,wav are allowed and not above 10MB in size</small>
                        </div>
                        <div class="form-group mt-4">
                            <div class="progress h-4 rounded" style="display: none;" id="progress2">
                                <div class="progress-bar bg-theme-6" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" ></div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <label>Publish to Admin</label>
                            <div class="mt-2">
                                <input type="checkbox" class="form-check-switch" @if(old('status', $audio->status) == '1') checked @endif value="1" name="status">
                            </div>
                        </div>
                        <div class="text-right mt-5">
                            <button type="button" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                            <button type="submit" class="btn btn-primary w-24">Save</button>
                        </div>
                    </div>
                    <!-- END: Form Layout -->
                </form>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){

        @if(!$audio->audio_id)
        $('#caption').empty();
        @endif

        $('input[name=image]').change(function(e){
            // var image = $(this).files[0];
            var formData = new FormData(); // Currently empty
            var _token = '{{ csrf_token() }}';
            formData.append('image', $(this)[0].files[0]);
            var url = '{{ route("upload.cover") }}';
            $('#progress').show();
            $("#progress").css("display", "block");

            $('.progress-bar').css('width',"0%");
            $('.progress-bar').html("0%");
            $.ajax({
                url: url,
                type: 'post',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                data: formData,
                cache:false,
                contentType: false,
                processData: false,
                beforeSubmit: function () {
                },
                xhr: function() {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress", function(evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = evt.loaded / evt.total;
                            percentComplete = parseInt(percentComplete * 100);
                            $('.progress-bar').css('width',percentComplete+"%");
                            $('.progress-bar').html(percentComplete+"%");
                            if (percentComplete > 29 && percentComplete < 60) {
                                $('.progress-bar').removeClass('bg-theme-6');
                                $('.progress-bar').addClass('bg-theme-12');
                            }else if (percentComplete > 59 && percentComplete < 100) {
                                $('.progress-bar').removeClass('bg-theme-12');
                                $('.progress-bar').addClass('bg-theme-1');
                            }else if (percentComplete === 100) {
                                $('.progress-bar').removeClass('bg-theme-12');
                                $('.progress-bar').addClass('bg-theme-9');
                            }
                        }
                    }, false);
                    return xhr;
                },
                success: function(data){
                    $('#progress').fadeOut();
                    $('#coverimage').val(data.imageName);
                    $('#img-display').show();
                    $('#img-display').html('<img style="width: 100%; height: 100%; object-fit: cover; vertical-align: middle;" src='+data.image+'>');
                    // console.log(data.message);

                }
            });
        });
    });

</script>
<script>
    $(document).ready(function(){
        $('input[name=audio]').change(function(e){
            // var image = $(this).files[0];
            var formData = new FormData(); // Currently empty
            var _token = '{{ csrf_token() }}';
            formData.append('audio', $(this)[0].files[0]);
            var auurl = '{{ route("upload.audio") }}';
            $('#progress2').show();
            $("#progress2").css("display", "block");
            $('.progress-bar').css('width',"0%");
            $('.progress-bar').html("0%");
            $.ajax({
                url: auurl,
                type: 'post',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                data: formData,
                cache:false,
                contentType: false,
                processData: false,
                beforeSubmit: function () {
                },
                xhr: function() {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress", function(evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = evt.loaded / evt.total;
                            percentComplete = parseInt(percentComplete * 100);
                            $('.progress-bar').css('width',percentComplete+"%");
                            $('.progress-bar').html(percentComplete+"%");
                            if (percentComplete > 29 && percentComplete < 60) {
                                $('.progress-bar').removeClass('bg-theme-6');
                                $('.progress-bar').addClass('bg-theme-12');
                            }else if (percentComplete > 59 && percentComplete < 100) {
                                $('.progress-bar').removeClass('bg-theme-12');
                                $('.progress-bar').addClass('bg-theme-1');
                            }else if (percentComplete === 100) {
                                $('.progress-bar').removeClass('bg-theme-12');
                                $('.progress-bar').addClass('bg-theme-9');
                            }
                        }
                    }, false);
                    return xhr;
                },
                success: function(data){
                    $('#progress2').fadeOut();
                    $('#audio').val(data.url);
                    $('#duration').val(data.duration);
                    $('#fext').val(data.ext);
                    $('#fsize').val(data.size);

                },
                error: function(e){
                    if(e.status == 422){

                        $.toast({
                            heading: 'Oh snap!',
                            text: e.responseJSON.errors.audio[0],
                            icon: 'error',
                            loader: true,        // Change it to false to disable loader
                            loaderBg: '#bf441d',  // To change the background
                            position: 'top-right',
                            icon: 'error',
                        });
                    }
                    $.toast({
                        heading: 'Oh snap!',
                        text: 'Oops!! Something went wrong',
                        icon: 'error',
                        loader: true,        // Change it to false to disable loader
                        loaderBg: '#bf441d',  // To change the background
                        position: 'top-right',
                        icon: 'error',
                    });
                }
            });
        });
    });

</script>
@endsection

resources/views/portal/user/audio/index.blade.php
@extends('portal.user.layout')
@section('title', 'All Audio Shared')
@section('content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.user.audio.create') }}" class="btn btn-primary shadow-md mr-2">Upload New Audio</a>
        <div class="dropdown">
            <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
        </div>
        <div class="hidden md:block mx-auto text-gray-600">Showing @if($audios->total() < 2) 1 @else 1 to {{ $audios->total() }} @endif of {{ $audios->total() }} entries</div>

    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        @if (count($audios) > 0)
            <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">Cover</th>
                <th class="whitespace-nowrap">Caption</th>
                <th class="text-center whitespace-nowrap">Created By</th>
                <th class="text-center whitespace-nowrap">Status</th>
                <th class="text-center whitespace-nowrap">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($audios as $audio)

            <tr class="intro-x">
                <td class="w-40">
                    <div class="flex">
                        <div class="w-10 h-10 image-fit zoom-in">
                            <img alt="{{ \Str::limit(\Str::slug($audio->caption), 10) }}" class="tooltip rounded-full" src="{{ asset($audio->image) }}" title="{{ \Str::limit($audio->caption, 10) }}">
                        </div>
                    </div>
                </td>
                <td>
                    <a href="" class="font-medium whitespace-nowrap">{{ \Str::limit($audio->caption, 10) }}</a>
                </td>
                <td class="text-center">{{ $audio->user->name }}</td>
                <td class="w-40">
                    @if($audio->status == '0')
                        <span class="text-theme-6"> Draft</span>
                    @elseif($audio->status == '1')
                        <span class="text-theme-12"> Pending</span>
                    @elseif($audio->status == '2')
                        <span class="text-theme-9"> Published</span>
                    @endif
                </td>
                <td class="table-report__action w-56">
                    <div class="flex justify-center items-center">
                        <a class="flex items-center mr-3" href="{{ route('portal.user.audio.edit', $audio->audio_id) }}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                        <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal{{ $audio->audio_id }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                    </div>
                </td>
            </tr>
            @push('audio-delete-modal')
                @include('portal.user.inc.audio-delete-modal', ['audio' => $audio])
            @endpush
            @endforeach

            </tbody>
        </table>
        @else
            <div class="col-12 alert alert-danger"><i data-feather="alert-octagon"></i> Oops!! No Audio Record Found.</div>
        @endif
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
        <ul class="pagination">
            {!! $audios->links() !!}
        </ul>
    </div>
    <!-- END: Pagination -->
</div>

@endsection
@section('scripts')
    <script>
        $('.item').on('change', function () {
            alert('');
            var val = $(this).val();
            window.location = window.location.href+'?items='+val;
        });
    </script>
@endsection