routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'AudioController@home')->name('home');
//    ->middleware('auth');

Route::get('/download/{audio}', 'AudioController@getDownload')->name('download');
Route::post('/send-code', 'ActivationCodeController@sendCode')->name('verify.code.send');
Auth::routes();

Route::prefix('portal')->name('portal.')->middleware('auth')->group(function () {
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'AudioController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AudioController@all')->name('home');
            Route::get('/create', 'AudioController@create')->name('create');
            Route::get('/pending', 'AudioController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AudioController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
        });
    });
    Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('audio')->name('audio.')->group(function () {
            Route::get('/', 'AdminController@allAudio')->name('home');
            Route::get('/create', 'AdminController@create')->name('create');
            Route::get('/pending', 'AdminController@pending')->name('pending');
            Route::get('/edit/{audio}', 'AdminController@edit')->name('edit');
            Route::post('/store', 'AudioController@store')->name('store');
            Route::patch('/update/{audio}', 'AudioController@update')->name('update');
            Route::get('/delete/{audio}', 'AudioController@destroy')->name('delete');
            Route::get('/publish/{audio}', 'AdminController@publish')->name('publish');
            Route::get('/reject/{audio}', 'AdminController@reject')->name('reject');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'level',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function audio()
    {
        return $this->hasMany(Audio::class);
    }

    public function isAdmin()
    {
        if (\Auth::check()){
            if (\Auth::user()->level == '1'){
                return true;
            }
            return false;
        }
        return false;
    }
}

resources/views/portal/user/inc/alert.blade.php
<div class="alert @if (Session::has('success')) alert-success @elseif(Session::has('error')) alert-danger @else d-none @endif alert-dismissible show flex items-center mb-2" role="alert">
    @if(Session::has('success')) <i data-feather="alert-circle" class="w-6 h-6 mr-2"></i>  {{ Session::get('success') }} @elseif(Session::has('error'))  <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> {{ Session::get('error') }} @endif
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
</div>

resources/views/portal/user/inc/audio-delete-modal.blade.php
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal{{ $audio->audio_id }}" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete {{ \Str::limit($audio->caption, 10) }} records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <a href="{{ route('portal.user.audio.delete', $audio->audio_id) }}" class="btn btn-danger w-24">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END: Delete Confirmation Modal -->

resources/views/portal/user/inc/msidebar.blade.php
<!-- BEGIN: Mobile Menu -->
<div class="mobile-menu md:hidden">
    <div class="mobile-menu-bar">
        <a href="" class="flex mr-auto">
            <img alt="{{ $appName }}" class="w-50" style="width: 30%;" src="{{ asset('images/logo-w.png') }}">
        </a>
        <a href="javascript:;" id="mobile-menu-toggler"> <i data-feather="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
    </div>
    <ul class="border-t border-theme-29 py-5 hidden">
        <li>
            <a href="{{ route('portal.user.home') }}" class="menu <?php if(isset($page) && $page == 'home'){ echo 'menu--active'; } ?>">
                <div class="menu__icon"> <i data-feather="home"></i> </div>
                <div class="menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.home') }}" class="menu @if(\Route::current()->getName() == 'portal.user.audio.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="upload"></i> </div>
                <div class="menu__title">  All Audio </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.create') }}" class="menu @if(\Route::current()->getName() == 'portal.user.audio.create') menu--active @endif">
                <div class="menu__icon"> <i data-feather="upload"></i> </div>
                <div class="menu__title">  Upload Audio </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.pending') }}" class="menu @if(\Route::current()->getName() == 'portal.user.audio.pending') menu--active @endif">
                <div class="menu__icon"> <i data-feather="headphones"></i> </div>
                <div class="menu__title"> Pending Audio </div>
            </a>
        </li>
    </ul>
</div>
<!-- END: Mobile Menu -->

resources/views/portal/user/inc/navbar.blade.php
<!-- BEGIN: Top Bar -->
<div class="top-bar">
    <!-- BEGIN: Breadcrumb -->
    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <a href="{{ route('portal.user.home')   }}">Home</a> <i data-feather="chevron-right" class="breadcrumb__icon"></i> <a href="" class="breadcrumb--active">@yield('title')</a> </div>
    <!-- END: Breadcrumb -->
    <!-- BEGIN: Search -->
    <div class="intro-x relative mr-3 sm:mr-6">
        <div class="search hidden sm:block">
            <input type="text" class="search__input form-control border-transparent placeholder-theme-13" placeholder="Search...">
            <i data-feather="search" class="search__icon dark:text-gray-300"></i>
        </div>
    </div>
    <!-- END: Search -->
    <!-- BEGIN: Account Menu -->
    <div class="intro-x dropdown w-8 h-8">
        <div class="dropdown-toggle w-8 h-8 rounded-full overflow-hidden shadow-lg image-fit zoom-in" role="button" aria-expanded="false">
            <img alt="{{ \Auth::user()->name }}" src="{{ asset('dist/images/profile-6.jpg') }}">
        </div>
        <div class="dropdown-menu w-56">
            <div class="dropdown-menu__content box bg-theme-26 dark:bg-dark-6 text-white">
                <div class="p-4 border-b border-theme-27 dark:border-dark-3">
                    <div class="font-medium">{{ \Auth::user()->name }}</div>
                    <div class="text-xs text-theme-28 mt-0.5 dark:text-gray-600">User </div>
                </div>
                <div class="p-2 border-t border-theme-27 dark:border-dark-3">
                    <a  href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" class="flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-1 dark:hover:bg-dark-3 rounded-md"> <i data-feather="toggle-right" class="w-4 h-4 mr-2"></i> Logout </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- END: Account Menu -->
</div>
<!-- END: Top Bar -->

resources/views/portal/user/inc/scripts.blade.php
<!-- BEGIN: JS Assets-->
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=0&libraries=places"></script>
<script src="{{ asset('dist/js/app.js') }}"></script>
<script src="{{ asset('js/jquery-3.6.0.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery-toast.min.js') }}"></script>
<!-- END: JS Assets-->

resources/views/portal/user/inc/sidebar.blade.php
<!-- BEGIN: Side Menu -->
<nav class="side-nav">
    <a href="{{ route('portal.user.home') }}" class="intro-x flex items-center pl-5 pt-4">
        <img alt="{{ $appName }}" class="w-50" style="width: 70%;" src="{{ asset('images/logo-w.png') }}">
    </a>
    <div class="side-nav__devider my-6"></div>
    <ul>
        <li>
            <a href="{{ route('portal.user.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.user.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="home"></i> </div>
                <div class="side-menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.user.audio.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="play-circle"></i> </div>
                <div class="side-menu__title">  All Audio </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.create') }}" class="side-menu @if(\Route::current()->getName() == 'portal.user.audio.create') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="upload"></i> </div>
                <div class="side-menu__title">  Upload Audio </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.user.audio.pending') }}" class="side-menu @if(\Route::current()->getName() == 'portal.user.audio.pending') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="headphones"></i> </div>
                <div class="side-menu__title"> Pending Audio </div>
            </a>
        </li>

    </ul>
</nav>
<!-- END: Side Menu -->

resources/views/portal/user/inc/styles.blade.php
<link href="{{ asset('dist/images/icon.png') }}" rel="shortcut icon">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="{{ $appCr }}">
<!-- BEGIN: CSS Assets-->
{{--<link rel="stylesheet" href="{{ asset('css/bulma.css') }}" />--}}
<link rel="stylesheet" href="{{ asset('css/boxicons.css') }}" />
<link rel="stylesheet" href="{{ asset('dist/css/app.css') }}" />
<link rel="stylesheet" href="{{ asset('css/jquery-toast.min.css') }}" type="text/css">